name: migscourier
description: Rider application for Migs Marketplace.

publish_to: 'none'

version: 1.5.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.0
  date_range_picker: ^1.0.7
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^5.0.0+4
  flutter_slidable: ^0.6.0
  font_awesome_flutter: ^9.0.0
  geocoder: ^0.2.1
  geolocator: ^7.0.3
  http: ^0.13.3
  modal_progress_hud: ^0.1.3
  package_info: ^2.0.0
  provider: ^5.0.0
  rxdart: ^0.27.0
  toggle_switch: ^0.1.9
  url_launcher: ^6.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar-male.jpg
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/launcher_icon.jpg

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Biryani-Regular.ttf
        - asset: assets/fonts/Biryani-Bold.ttf
          weight: 700
